apiVersion: v1 
kind: Service 
metadata: 
  name: vprocache01
spec:
  selector:
    app: vpromc
  ports:
  - name: vpromc-port
    protocol: TCP
    port: 11211
    targetPort: 11211
  type: ClusterIP


